name: default
channels:
  - conda-forge
  - defaults
dependencies:
  # build
  - compilers
  - make
  - scons
  - git-lfs
  # link
  - apr
  - boost
  - bottleneck
  - cfitsio
  - deprecated
  - doxygen
  - esutil
  - fftw
  - galsim
  - gsl
  - libaprutil
  - lmfit
  - minuit2
  - mpi4py
  - mpich
  - ndarray
  - numexpr
  - starlink-ast
  - treecorr
  - wcslib
  # python
  - astropy
  - cffi
  - cython
  - flake8
  - future
  - h5py
  - healpy
  - matplotlib
  - numpy
  - pandas
  - pep8-naming
  - pip
  - pybind11
  - pytables
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-forked
  - pytest-xdist
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - sqlalchemy
  - ws4py
  - pip:
    - git+https://github.com/BuhtigithuB/pytest_session2file@8a97d3a
